services:
  - type: web
    runtime: static
    name: kyoute-keisya-calc
    repo: https://github.com/Stasshe/Kyoute-Keisya-calc
    buildCommand: npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_IS_DEV_SERVER
        value: "true"
    previews:
      generation: automatic
